[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-python-project"
version = "0.1.0"
description = "My Python project"
dependencies = [
    # Your regular Python dependencies
    "requests>=2.25.0",
    "click>=8.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black",
    "isort",
    "mypy",
    # Add ty-find as a dev dependency from GitHub
    "ty-find @ git+https://github.com/mojzis/ty-find.git",
]

# With uv - this is the cleanest approach
[dependency-groups]
dev = [
    "pytest>=6.0",
    "black",
    "isort", 
    "mypy",
    "ty-find @ git+https://github.com/mojzis/ty-find.git",
]